FROM python:3.10-slim

ENV PYTHONDONTWRITEBYTECODE=1 \
    PYTHONUNBUFFERED=1

RUN adduser --disabled-password --gecos '' appuser

WORKDIR /project

COPY ./code/requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

COPY ./code .

RUN chown -R appuser /project

USER appuser

CMD ["gunicorn", "--bind", "0.0.0.0:8000", "app.main:app"]
