version: '3.9'
services:
  jenkins:
    build: .
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - jenkins_home:/var/jenkins_home
    networks:
      - jenkins
    restart: always

networks:
  jenkins:

volumes:
  jenkins_home: