
apiVersion: v1
kind: Service
metadata:
  name: weather-api-service
  namespace: sadik 
spec:
  type: NodePort  
  ports:
    - port: 80
      targetPort: 8788
      nodePort: 30003  
      protocol: TCP
  selector:
    app: weather-api